home:
  label: home
  url: /home
  select: site/index
debt:
  label: customer_charge
  url: /customer
  select: customer
apps:
  label: applications
  url: /apps
  select: applications new_customer
map:
  label: map
  url: /map
  select: map