home:
  label: საწყისი
  url: /home
  select: site/index
debt:
  label: ხარჯი
  url: /customer
  select: customer
apps:
  label: განცხადებები
  url: /apps
  select: applications new_customer
map:
  label: რუკა
  url: /map
  select: map