main:
  label: ძირითადი
  url: /apps/new_customer/show/:id
  select: new_customer/show
customers:
  label: აბონენტები
  url: /apps/new_customer/show/:id/items
  select: new_customer/items new_customer/new_item new_customer/edit_item
payments:
  label: გადახდები
  url: /apps/new_customer/show/:id/payments
  select: new_customer/payments new_customer/new_payment new_customer/edit_payment
docs:
  label: დოკუმენტები
  url: /apps/new_customer/show/:id/docs
  select: new_customer/docs new_customer/new_doc
notes:
  label: შენიშვნები
  url: /apps/new_customer/show/:id/notes
  select: new_customer/notes new_customer/new_note