require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Call::CallMobilesController do

  # This should return the minimal set of attributes required to create a valid
  # Call::CallMobile. As you add validations to Call::CallMobile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Call::CallMobilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all call_call_mobiles as @call_call_mobiles" do
      call_mobile = Call::CallMobile.create! valid_attributes
      get :index, {}, valid_session
      assigns(:call_call_mobiles).should eq([call_mobile])
    end
  end

  describe "GET show" do
    it "assigns the requested call_call_mobile as @call_call_mobile" do
      call_mobile = Call::CallMobile.create! valid_attributes
      get :show, {:id => call_mobile.to_param}, valid_session
      assigns(:call_call_mobile).should eq(call_mobile)
    end
  end

  describe "GET new" do
    it "assigns a new call_call_mobile as @call_call_mobile" do
      get :new, {}, valid_session
      assigns(:call_call_mobile).should be_a_new(Call::CallMobile)
    end
  end

  describe "GET edit" do
    it "assigns the requested call_call_mobile as @call_call_mobile" do
      call_mobile = Call::CallMobile.create! valid_attributes
      get :edit, {:id => call_mobile.to_param}, valid_session
      assigns(:call_call_mobile).should eq(call_mobile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Call::CallMobile" do
        expect {
          post :create, {:call_call_mobile => valid_attributes}, valid_session
        }.to change(Call::CallMobile, :count).by(1)
      end

      it "assigns a newly created call_call_mobile as @call_call_mobile" do
        post :create, {:call_call_mobile => valid_attributes}, valid_session
        assigns(:call_call_mobile).should be_a(Call::CallMobile)
        assigns(:call_call_mobile).should be_persisted
      end

      it "redirects to the created call_call_mobile" do
        post :create, {:call_call_mobile => valid_attributes}, valid_session
        response.should redirect_to(Call::CallMobile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved call_call_mobile as @call_call_mobile" do
        # Trigger the behavior that occurs when invalid params are submitted
        Call::CallMobile.any_instance.stub(:save).and_return(false)
        post :create, {:call_call_mobile => {  }}, valid_session
        assigns(:call_call_mobile).should be_a_new(Call::CallMobile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Call::CallMobile.any_instance.stub(:save).and_return(false)
        post :create, {:call_call_mobile => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested call_call_mobile" do
        call_mobile = Call::CallMobile.create! valid_attributes
        # Assuming there are no other call_call_mobiles in the database, this
        # specifies that the Call::CallMobile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Call::CallMobile.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => call_mobile.to_param, :call_call_mobile => { "these" => "params" }}, valid_session
      end

      it "assigns the requested call_call_mobile as @call_call_mobile" do
        call_mobile = Call::CallMobile.create! valid_attributes
        put :update, {:id => call_mobile.to_param, :call_call_mobile => valid_attributes}, valid_session
        assigns(:call_call_mobile).should eq(call_mobile)
      end

      it "redirects to the call_call_mobile" do
        call_mobile = Call::CallMobile.create! valid_attributes
        put :update, {:id => call_mobile.to_param, :call_call_mobile => valid_attributes}, valid_session
        response.should redirect_to(call_mobile)
      end
    end

    describe "with invalid params" do
      it "assigns the call_call_mobile as @call_call_mobile" do
        call_mobile = Call::CallMobile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Call::CallMobile.any_instance.stub(:save).and_return(false)
        put :update, {:id => call_mobile.to_param, :call_call_mobile => {  }}, valid_session
        assigns(:call_call_mobile).should eq(call_mobile)
      end

      it "re-renders the 'edit' template" do
        call_mobile = Call::CallMobile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Call::CallMobile.any_instance.stub(:save).and_return(false)
        put :update, {:id => call_mobile.to_param, :call_call_mobile => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested call_call_mobile" do
      call_mobile = Call::CallMobile.create! valid_attributes
      expect {
        delete :destroy, {:id => call_mobile.to_param}, valid_session
      }.to change(Call::CallMobile, :count).by(-1)
    end

    it "redirects to the call_call_mobiles list" do
      call_mobile = Call::CallMobile.create! valid_attributes
      delete :destroy, {:id => call_mobile.to_param}, valid_session
      response.should redirect_to(call_call_mobiles_url)
    end
  end

end
