account:
  label: ანგარიშის მართვა
  register: მომხმარებლის რეგისტრაცია
  account: თქვენი ანგარიში
  email_confirm: ელ. ფოსტის დადასტურება
  mobile_confirm: მობილურის დადასტურება
connect_app:
  label: ქსელზე მიერთება
  tariffs: განაკვეთები
  rules: შევსების წესები
policy:
  label: საიტის პოლიტიკა
  terms: მომსახურების პირობები
  privacy: კონფიდენციალურობა