development:
  host: localhost
  database: telasi_service_development

test:
  host: localhost
  database: telasi_service_test

# set these environment variables on your prod server
production:
  host: localhost
  database: telasi_service_prod
