development:
  host: localhost
  database: telasi_service_development

test:
  host: localhost
  database: telasi_service_test

# set these environment variables on your prod server
production:
  host: localhost
  database: telasi_service_prod
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
