tariff_01:
  id: 1
  voltage: '0.220'
  voltage_alt: '220 ვ'
  power_kwt: 1-10
  days_to_complete: 35
  days_to_complete_without_resolution: 20
  price_gel: 400
tariff_02:
  id: 2
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power_kwt: 1-10
  days_to_complete: 35
  days_to_complete_without_resolution: 20
  price_gel: 1200
tariff_03:
  id: 3
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power_kwt: 11-30
  days_to_complete: 40
  days_to_complete_without_resolution: 20
  price_gel: 4700
tariff_04:
  id: 4
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power_kwt: 31-50
  days_to_complete: 40
  days_to_complete_without_resolution: 20
  price_gel: 7000
tariff_05:
  id: 5
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power_kwt: 51-80
  days_to_complete: 45
  days_to_complete_without_resolution: 20
  price_gel: 10500
tariff_06:
  id: 6
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power_kwt: 81-100
  days_to_complete: 45
  days_to_complete_without_resolution: 20
  price_gel: 12000
tariff_07:
  id: 7
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power_kwt: 101-125
  days_to_complete: 45
  days_to_complete_without_resolution: 20
  price_gel: 14000
tariff_08:
  id: 8
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power_kwt: 126-200
  days_to_complete: 45
  days_to_complete_without_resolution: 20
  price_gel: 2150
tariff_09:
  id: 9
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power_kwt: 201-320
  days_to_complete: 60
  days_to_complete_without_resolution: 20
  price_gel: 33000
tariff_10:
  id: 10
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power_kwt: 321-500
  days_to_complete: 60
  days_to_complete_without_resolution: 20
  price_gel: 50500
tariff_11:
  id: 11
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power_kwt: 501-800
  days_to_complete: 90
  days_to_complete_without_resolution: 20
  price_gel: 80000
tariff_12:
  id: 12
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power_kwt: 801-1000
  days_to_complete: 90
  days_to_complete_without_resolution: 20
  price_gel: 100000
tariff_13:
  id: 13
  voltage: '6/10'
  voltage_alt: '6/10 კვ'
  power_kwt: 1-500
  days_to_complete: 60
  days_to_complete_without_resolution: 20
  price_gel: 48500
tariff_14:
  id: 14
  voltage: '6/10'
  voltage_alt: '6/10 კვ'
  power_kwt: 501-1000
  days_to_complete: 90
  days_to_complete_without_resolution: 40
  price_gel: 94000
tariff_15:
  id: 15
  voltage: '6/10'
  voltage_alt: '6/10 კვ'
  power_kwt: 1001-1500
  days_to_complete: 90
  days_to_complete_without_resolution: 40
  price_gel: 137000
tariff_16:
  id: 16
  voltage: '6/10'
  voltage_alt: '6/10 კვ'
  power_kwt: 1501-2000
  days_to_complete: 90
  days_to_complete_without_resolution: 40
  price_gel: 177000
tariff_17:
  id: 17
  voltage: '6/10'
  voltage_alt: '6/10 კვ'
  power_kwt: 2001-3000
  days_to_complete: 90
  days_to_complete_without_resolution: 40
  price_gel: 257500
tariff_18:
  id: 18
  voltage: '6/10'
  voltage_alt: '6/10 კვ'
  power_kwt: 3001-5000
  days_to_complete: 90
  days_to_complete_without_resolution: 40
  price_gel: 416000