1:
  voltage: '0.220'
  voltage_alt: '220 ვ'
  power: 1-10
  complete: 35
  price: 400
2:
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power: 1-10
  complete: 35
  price: 1200
3:
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power: 11-30
  complete: 40
  price: 4700
4:
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power: 31-50
  complete: 40
  price: 7000
5:
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power: 51-80
  complete: 45
  price: 10500
6:
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power: 81-100
  complete: 45
  price: 12000
7:
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power: 101-125
  complete: 45
  price: 14000
8:
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power: 126-200
  complete: 45
  price: 2150
9:
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power: 201-320
  complete: 60
  price: 33000
10:
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power: 321-500
  complete: 60
  price: 50500
11:
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power: 501-800
  complete: 90
  price: 80000
12:
  voltage: '0.380'
  voltage_alt: '380 ვ'
  power: 801-1000
  complete: 90
  price: 100000
13:
  voltage: '6/10'
  voltage_alt: '6/10 კვ'
  power: 1-500
  complete: 60
  price: 48500
14:
  voltage: '6/10'
  voltage_alt: '6/10 კვ'
  power: 501-1000
  complete: 90
  price: 94000
15:
  voltage: '6/10'
  voltage_alt: '6/10 კვ'
  power: 1001-1500
  complete: 90
  price: 137000
16:
  voltage: '6/10'
  voltage_alt: '6/10 კვ'
  power: 1501-2000
  complete: 90
  price: 177000
17:
  voltage: '6/10'
  voltage_alt: '6/10 კვ'
  power: 2001-3000
  complete: 90
  price: 257500
18:
  voltage: '6/10'
  voltage_alt: '6/10 კვ'
  power: 3001-5000
  complete: 90
  price: 416000